-- MySQL Script generated by MySQL Workbench
-- Wed Aug 15 12:31:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trapit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trapit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trapit` DEFAULT CHARACTER SET utf8 ;
USE `trapit` ;

-- -----------------------------------------------------
-- Table `trapit`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`role` ;

CREATE TABLE IF NOT EXISTS `trapit`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE,
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`user` ;

CREATE TABLE IF NOT EXISTS `trapit`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(256) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `role_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `user_role_fk_idx` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_role_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `trapit`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`site` ;

CREATE TABLE IF NOT EXISTS `trapit`.`site` (
  `site_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`site_id`),
  UNIQUE INDEX `site_id_UNIQUE` (`site_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`path`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`path` ;

CREATE TABLE IF NOT EXISTS `trapit`.`path` (
  `path_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`path_id`),
  UNIQUE INDEX `path_id_UNIQUE` (`path_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`media` ;

CREATE TABLE IF NOT EXISTS `trapit`.`media` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `empty` TINYINT NOT NULL DEFAULT 0,
  `image` TINYINT NOT NULL DEFAULT 1,
  `interesting` TINYINT NOT NULL DEFAULT 0,
  `comment` TEXT NULL DEFAULT NULL,
  `site_id` INT NOT NULL,
  `path_id` INT NOT NULL,
  `last_user_id` INT NULL DEFAULT NULL,
  `last_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`media_id`),
  UNIQUE INDEX `media_id_UNIQUE` (`media_id` ASC) VISIBLE,
  INDEX `media_site_fk_idx` (`site_id` ASC) VISIBLE,
  INDEX `media_path_fk_idx` (`path_id` ASC) VISIBLE,
  INDEX `fk_media_user1_idx` (`last_user_id` ASC) VISIBLE,
  CONSTRAINT `media_site_fk`
    FOREIGN KEY (`site_id`)
    REFERENCES `trapit`.`site` (`site_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `media_path_fk`
    FOREIGN KEY (`path_id`)
    REFERENCES `trapit`.`path` (`path_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_user1`
    FOREIGN KEY (`last_user_id`)
    REFERENCES `trapit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`tag` ;

CREATE TABLE IF NOT EXISTS `trapit`.`tag` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `parent_tag_id` INT NULL DEFAULT NULL,
  `input` TINYINT NOT NULL DEFAULT 0,
  `checkbox` TINYINT NOT NULL,
  `slo_name` VARCHAR(64) NULL,
  `eng_name` VARCHAR(64) NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC) VISIBLE,
  INDEX `tag_parent_fk_idx` (`parent_tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_tag_parent`
    FOREIGN KEY (`parent_tag_id`)
    REFERENCES `trapit`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`media_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`media_tag` ;

CREATE TABLE IF NOT EXISTS `trapit`.`media_tag` (
  `media_tag_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  `input_value` INT NULL DEFAULT NULL,
  UNIQUE INDEX `media_tag_id_UNIQUE` (`media_tag_id` ASC) VISIBLE,
  PRIMARY KEY (`media_tag_id`),
  INDEX `media_tag_user_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `media_tag_tag_fk_idx` (`tag_id` ASC) VISIBLE,
  INDEX `media_tag_media_fk_idx` (`media_id` ASC) VISIBLE,
  CONSTRAINT `media_tag_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `trapit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `media_tag_tag_fk`
    FOREIGN KEY (`tag_id`)
    REFERENCES `trapit`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `media_tag_media_fk`
    FOREIGN KEY (`media_id`)
    REFERENCES `trapit`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`project` ;

CREATE TABLE IF NOT EXISTS `trapit`.`project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`project_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`project_tag` ;

CREATE TABLE IF NOT EXISTS `trapit`.`project_tag` (
  `project_tag_id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`project_tag_id`),
  INDEX `project_tag_tag_fk_idx` (`tag_id` ASC) VISIBLE,
  UNIQUE INDEX `project_tag_id_UNIQUE` (`project_tag_id` ASC) VISIBLE,
  INDEX `project_tag_project_fk` (`project_id` ASC) VISIBLE,
  CONSTRAINT `project_tag_project_fk`
    FOREIGN KEY (`project_id`)
    REFERENCES `trapit`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_tag_tag_fk`
    FOREIGN KEY (`tag_id`)
    REFERENCES `trapit`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`media_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`media_project` ;

CREATE TABLE IF NOT EXISTS `trapit`.`media_project` (
  `media_project_id` INT NOT NULL AUTO_INCREMENT,
  `media_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`media_project_id`),
  UNIQUE INDEX `media_project_id_UNIQUE` (`media_project_id` ASC) VISIBLE,
  INDEX `fk_media_project_media1_idx` (`media_id` ASC) VISIBLE,
  INDEX `fk_media_project_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_media_project_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `trapit`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `trapit`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
