UPDATE `trapit`.`tag` SET `slo_name` = 'Vrsta', `eng_name` = 'Species' WHERE (`tag_id` = '1');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelenjad', `eng_name` = 'Red Deer' WHERE (`tag_id` = '2');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tele', `eng_name` = 'Claf' WHERE (`tag_id` = '3');
UPDATE `trapit`.`tag` SET `slo_name` = 'Junica', `eng_name` = 'Heifer' WHERE (`tag_id` = '4');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '5');
UPDATE `trapit`.`tag` SET `slo_name` = 'Košuta', `eng_name` = 'Hind' WHERE (`tag_id` = '6');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen', `eng_name` = 'Red Deer' WHERE (`tag_id` = '7');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(2-4)', `eng_name` = 'Stag(2-4)' WHERE (`tag_id` = '8');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(5-10)', `eng_name` = 'Stag(5-10)' WHERE (`tag_id` = '9');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(10+)', `eng_name` = 'Stag(10+)' WHERE (`tag_id` = '10');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjad', `eng_name` = 'Roe Deer' WHERE (`tag_id` = '11');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '12');
UPDATE `trapit`.`tag` SET `slo_name` = 'Gumbar', `eng_name` = 'Young Deer' WHERE (`tag_id` = '13');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '14');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladica', `eng_name` = 'Juvenile' WHERE (`tag_id` = '15');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srna', `eng_name` = 'Doe' WHERE (`tag_id` = '16');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjak', `eng_name` = 'Buck' WHERE (`tag_id` = '17');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjak (srednje star)', `eng_name` = 'Buck (middle-age)' WHERE (`tag_id` = '18');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjak (star)', `eng_name` = 'Buck (old)' WHERE (`tag_id` = '19');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divji Prašič', `eng_name` = 'Wild Boar' WHERE (`tag_id` = '20');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '21');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ozimec', `eng_name` = 'Young Boar' WHERE (`tag_id` = '22');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '23');
UPDATE `trapit`.`tag` SET `slo_name` = 'Svinja', `eng_name` = 'Pig' WHERE (`tag_id` = '24');
UPDATE `trapit`.`tag` SET `slo_name` = 'Merjasec', `eng_name` = 'Boar' WHERE (`tag_id` = '25');
UPDATE `trapit`.`tag` SET `slo_name` = 'Rjavi Medved', `eng_name` = 'Brown Bear' WHERE (`tag_id` = '26');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '27');
UPDATE `trapit`.`tag` SET `slo_name` = 'Medvedka', `eng_name` = 'Bear (female)' WHERE (`tag_id` = '28');
UPDATE `trapit`.`tag` SET `slo_name` = 'Medved', `eng_name` = 'Bear (male)' WHERE (`tag_id` = '29');
UPDATE `trapit`.`tag` SET `slo_name` = '200kg+', `eng_name` = '200kg+' WHERE (`tag_id` = '30');
UPDATE `trapit`.`tag` SET `slo_name` = 'Damjek', `eng_name` = 'Fallow Deer' WHERE (`tag_id` = '31');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tele', `eng_name` = 'Calf' WHERE (`tag_id` = '32');
UPDATE `trapit`.`tag` SET `slo_name` = 'Junica', `eng_name` = 'Heifer' WHERE (`tag_id` = '33');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '34');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(2-4)', `eng_name` = 'Stag(2-4)' WHERE (`tag_id` = '35');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(5-10)', `eng_name` = 'Stag(5-10)' WHERE (`tag_id` = '36');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(10+)', `eng_name` = 'Stag(10+)' WHERE (`tag_id` = '37');
UPDATE `trapit`.`tag` SET `slo_name` = 'Košuta', `eng_name` = 'Hind' WHERE (`tag_id` = '38');
UPDATE `trapit`.`tag` SET `slo_name` = 'Gams', `eng_name` = 'Chamois' WHERE (`tag_id` = '39');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '40');
UPDATE `trapit`.`tag` SET `slo_name` = 'Koza', `eng_name` = 'Goat (female)' WHERE (`tag_id` = '41');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozel', `eng_name` = 'Goat (male)' WHERE (`tag_id` = '42');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozorog', `eng_name` = 'Alpine Ibex' WHERE (`tag_id` = '43');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '44');
UPDATE `trapit`.`tag` SET `slo_name` = 'Koza', `eng_name` = 'Goat (female)' WHERE (`tag_id` = '45');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozel', `eng_name` = 'Goat (male)' WHERE (`tag_id` = '46');
UPDATE `trapit`.`tag` SET `slo_name` = 'Muflon', `eng_name` = 'Mouflon' WHERE (`tag_id` = '47');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '48');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ovca', `eng_name` = 'Sheep' WHERE (`tag_id` = '49');
UPDATE `trapit`.`tag` SET `slo_name` = 'Oven', `eng_name` = 'Ram' WHERE (`tag_id` = '50');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ptica pevka', `eng_name` = 'Songbird' WHERE (`tag_id` = '51');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ščinkavec', `eng_name` = 'Finch' WHERE (`tag_id` = '52');
UPDATE `trapit`.`tag` SET `slo_name` = 'Brglez', `eng_name` = 'Nuthach' WHERE (`tag_id` = '53');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kos', `eng_name` = 'Blackbird' WHERE (`tag_id` = '54');
UPDATE `trapit`.`tag` SET `slo_name` = 'Šoja', `eng_name` = 'Eurasian Jay' WHERE (`tag_id` = '55');
UPDATE `trapit`.`tag` SET `slo_name` = 'Velika Sinica', `eng_name` = 'Great Tit' WHERE (`tag_id` = '56');
UPDATE `trapit`.`tag` SET `slo_name` = 'Krokar', `eng_name` = 'Raven' WHERE (`tag_id` = '57');
UPDATE `trapit`.`tag` SET `slo_name` = 'Menišček', `eng_name` = 'Coal Tit' WHERE (`tag_id` = '58');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ujeda', `eng_name` = 'Raptor' WHERE (`tag_id` = '59');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kanja', `eng_name` = 'Buzzard' WHERE (`tag_id` = '60');
UPDATE `trapit`.`tag` SET `slo_name` = 'Belorepec', `eng_name` = 'White-tailed Eagle' WHERE (`tag_id` = '61');
UPDATE `trapit`.`tag` SET `slo_name` = 'Skobec', `eng_name` = 'Sparrowhawk' WHERE (`tag_id` = '62');
UPDATE `trapit`.`tag` SET `slo_name` = 'Planinski Orel', `eng_name` = 'Golden Eagle' WHERE (`tag_id` = '63');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kragulj', `eng_name` = 'Goshawk' WHERE (`tag_id` = '64');
UPDATE `trapit`.`tag` SET `slo_name` = 'Sova', `eng_name` = 'Owl' WHERE (`tag_id` = '65');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozača', `eng_name` = 'Ural Owl' WHERE (`tag_id` = '66');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lesna Sova', `eng_name` = 'Trawny Owl' WHERE (`tag_id` = '67');
UPDATE `trapit`.`tag` SET `slo_name` = 'Velika Uharica', `eng_name` = 'Eagle Owl' WHERE (`tag_id` = '68');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pegasta Sova', `eng_name` = 'Barn Owl' WHERE (`tag_id` = '69');
UPDATE `trapit`.`tag` SET `slo_name` = 'Čuk', `eng_name` = 'Little Owl' WHERE (`tag_id` = '70');
UPDATE `trapit`.`tag` SET `slo_name` = 'Veliki Skovik', `eng_name` = 'Eurasian Scops Owl' WHERE (`tag_id` = '71');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mali Skovik', `eng_name` = 'Eurasian Pygmy Owl' WHERE (`tag_id` = '72');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mala Uharica', `eng_name` = 'Long-eared Owl' WHERE (`tag_id` = '73');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kura', `eng_name` = 'Hen' WHERE (`tag_id` = '74');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divji Petelin', `eng_name` = 'Western Capercaillie' WHERE (`tag_id` = '75');
UPDATE `trapit`.`tag` SET `slo_name` = 'Gozdni Jereb', `eng_name` = 'Hazel Grouse' WHERE (`tag_id` = '76');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ruševec', `eng_name` = 'Black Grouse' WHERE (`tag_id` = '77');
UPDATE `trapit`.`tag` SET `slo_name` = 'Fazan', `eng_name` = 'Pheasant' WHERE (`tag_id` = '78');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jerebica', `eng_name` = 'Grey Partridge' WHERE (`tag_id` = '79');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kotorna', `eng_name` = 'Rock Partridge' WHERE (`tag_id` = '80');
UPDATE `trapit`.`tag` SET `slo_name` = 'Belka', `eng_name` = 'Ptarmigan' WHERE (`tag_id` = '81');
UPDATE `trapit`.`tag` SET `slo_name` = 'Golob', `eng_name` = 'Pidgeon' WHERE (`tag_id` = '82');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divja Grlica', `eng_name` = 'Turtle Dove' WHERE (`tag_id` = '83');
UPDATE `trapit`.`tag` SET `slo_name` = 'Duplar', `eng_name` = 'Stock Dove' WHERE (`tag_id` = '84');
UPDATE `trapit`.`tag` SET `slo_name` = 'Grivar', `eng_name` = 'Wood Pidgeon' WHERE (`tag_id` = '85');
UPDATE `trapit`.`tag` SET `slo_name` = 'Žolna', `eng_name` = 'Woodpecker' WHERE (`tag_id` = '86');
UPDATE `trapit`.`tag` SET `slo_name` = 'Črna Žolna', `eng_name` = 'Black Woodpecker' WHERE (`tag_id` = '87');
UPDATE `trapit`.`tag` SET `slo_name` = 'Zelena Žolna', `eng_name` = 'European Green Woodpecker' WHERE (`tag_id` = '88');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pivka', `eng_name` = 'Grey-headed Woodpecker' WHERE (`tag_id` = '89');
UPDATE `trapit`.`tag` SET `slo_name` = 'Veliki Detel', `eng_name` = 'Great Spotted Woodpecker' WHERE (`tag_id` = '90');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mali Detel', `eng_name` = 'Lesser Spotted Woodpecker' WHERE (`tag_id` = '91');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srednji Detel', `eng_name` = 'Middle Spotted Woodpecker' WHERE (`tag_id` = '92');
UPDATE `trapit`.`tag` SET `slo_name` = 'Belohrbti Detel', `eng_name` = 'White-tailed Woodpecker' WHERE (`tag_id` = '93');
UPDATE `trapit`.`tag` SET `slo_name` = 'Triprsti Detel', `eng_name` = 'Three-toed Woodpecker' WHERE (`tag_id` = '94');
UPDATE `trapit`.`tag` SET `slo_name` = 'Volk', `eng_name` = 'Wolf' WHERE (`tag_id` = '95');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '96');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '97');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '98');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '99');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kuna', `eng_name` = 'Marten' WHERE (`tag_id` = '100');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '101');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '102');
UPDATE `trapit`.`tag` SET `slo_name` = 'Šakal', `eng_name` = 'Jackal' WHERE (`tag_id` = '103');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '104');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '105');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '106');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '107');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divja Mačka', `eng_name` = 'Wildcat' WHERE (`tag_id` = '108');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '109');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '110');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ris', `eng_name` = 'Eurasian Lynx' WHERE (`tag_id` = '111');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '112');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '113');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '114');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '115');
UPDATE `trapit`.`tag` SET `slo_name` = 'Los', `eng_name` = 'Moose' WHERE (`tag_id` = '116');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tele', `eng_name` = 'Claf' WHERE (`tag_id` = '117');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '118');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '119');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vidra', `eng_name` = 'Otter' WHERE (`tag_id` = '120');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '121');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '122');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jazbec', `eng_name` = 'Badger' WHERE (`tag_id` = '123');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '124');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '125');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lisica', `eng_name` = 'Fox' WHERE (`tag_id` = '126');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '127');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '128');
UPDATE `trapit`.`tag` SET `slo_name` = 'Rosomah', `eng_name` = 'Wolverine' WHERE (`tag_id` = '129');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '130');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '131');
UPDATE `trapit`.`tag` SET `slo_name` = 'Bober', `eng_name` = 'Beaver' WHERE (`tag_id` = '132');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '133');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '134');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pes', `eng_name` = 'Dog' WHERE (`tag_id` = '135');
UPDATE `trapit`.`tag` SET `slo_name` = 'Domača Mačka', `eng_name` = 'Feral Cat' WHERE (`tag_id` = '136');
UPDATE `trapit`.`tag` SET `slo_name` = 'Veverica', `eng_name` = 'Squirrel' WHERE (`tag_id` = '137');
UPDATE `trapit`.`tag` SET `slo_name` = 'Polh', `eng_name` = 'Dormouse' WHERE (`tag_id` = '138');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jež', `eng_name` = 'European Hedgehog' WHERE (`tag_id` = '139');
UPDATE `trapit`.`tag` SET `slo_name` = 'Zober', `eng_name` = 'European Bison' WHERE (`tag_id` = '140');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mink', `eng_name` = 'American Mink' WHERE (`tag_id` = '141');
UPDATE `trapit`.`tag` SET `slo_name` = 'Nutrija', `eng_name` = 'Nutria' WHERE (`tag_id` = '142');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pižmovka', `eng_name` = 'Muskrat' WHERE (`tag_id` = '143');
UPDATE `trapit`.`tag` SET `slo_name` = 'Podlasica', `eng_name` = 'Weasel' WHERE (`tag_id` = '144');
UPDATE `trapit`.`tag` SET `slo_name` = 'Drugi Sesalci', `eng_name` = 'Other Mamals' WHERE (`tag_id` = '145');
UPDATE `trapit`.`tag` SET `slo_name` = 'Poljski Zajec', `eng_name` = 'Hare' WHERE (`tag_id` = '146');
UPDATE `trapit`.`tag` SET `slo_name` = 'Nedoločljiva', `eng_name` = 'Indistinguishable' WHERE (`tag_id` = '147');
UPDATE `trapit`.`tag` SET `slo_name` = 'Brez Živali', `eng_name` = 'No Animals' WHERE (`tag_id` = '148');
UPDATE `trapit`.`tag` SET `slo_name` = 'Število', `eng_name` = 'Number' WHERE (`tag_id` = '149');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vaba', `eng_name` = 'Bait' WHERE (`tag_id` = '150');
UPDATE `trapit`.`tag` SET `slo_name` = 'Brez Vabe', `eng_name` = 'No Bait' WHERE (`tag_id` = '151');
UPDATE `trapit`.`tag` SET `slo_name` = 'Koruza', `eng_name` = 'Corn' WHERE (`tag_id` = '152');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mrhovina', `eng_name` = 'Carrion' WHERE (`tag_id` = '153');
UPDATE `trapit`.`tag` SET `slo_name` = 'Solnica', `eng_name` = 'Salt Lick' WHERE (`tag_id` = '154');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jabolka', `eng_name` = 'Apples' WHERE (`tag_id` = '155');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tropine', `eng_name` = 'Grape Skins' WHERE (`tag_id` = '156');
UPDATE `trapit`.`tag` SET `slo_name` = 'Seno', `eng_name` = 'Hay' WHERE (`tag_id` = '157');
UPDATE `trapit`.`tag` SET `slo_name` = 'Sladkorna Pesa', `eng_name` = 'Sugar Beet' WHERE (`tag_id` = '158');
UPDATE `trapit`.`tag` SET `slo_name` = 'Slaščičarski Ostanki', `eng_name` = 'Bakery Leftovers' WHERE (`tag_id` = '159');
UPDATE `trapit`.`tag` SET `slo_name` = 'Druga Vaba', `eng_name` = 'Other Bait' WHERE (`tag_id` = '160');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vedenje', `eng_name` = 'Behaviour' WHERE (`tag_id` = '161');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pitje', `eng_name` = 'Drinking' WHERE (`tag_id` = '162');
UPDATE `trapit`.`tag` SET `slo_name` = 'Parjenje', `eng_name` = 'Mating' WHERE (`tag_id` = '163');
UPDATE `trapit`.`tag` SET `slo_name` = 'Bojevanje', `eng_name` = 'Fighting' WHERE (`tag_id` = '164');
UPDATE `trapit`.`tag` SET `slo_name` = 'Prehajanje', `eng_name` = 'Crossing' WHERE (`tag_id` = '165');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vohanje', `eng_name` = 'Sniffing' WHERE (`tag_id` = '166');
UPDATE `trapit`.`tag` SET `slo_name` = 'Opazovanje', `eng_name` = 'Observing' WHERE (`tag_id` = '167');
UPDATE `trapit`.`tag` SET `slo_name` = 'Iztrebljanje', `eng_name` = 'Defecation' WHERE (`tag_id` = '168');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kopanje', `eng_name` = 'Digging' WHERE (`tag_id` = '169');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lov', `eng_name` = 'Hunt' WHERE (`tag_id` = '170');
UPDATE `trapit`.`tag` SET `slo_name` = 'Oglašanje', `eng_name` = 'Calling' WHERE (`tag_id` = '171');
UPDATE `trapit`.`tag` SET `slo_name` = 'Markiranje', `eng_name` = 'Marking' WHERE (`tag_id` = '172');
UPDATE `trapit`.`tag` SET `slo_name` = 'Valjanje', `eng_name` = 'Rolling' WHERE (`tag_id` = '173');
UPDATE `trapit`.`tag` SET `slo_name` = 'Drugo', `eng_name` = 'Other' WHERE (`tag_id` = '174');
UPDATE `trapit`.`tag` SET `slo_name` = 'Hranjenje', `eng_name` = 'Feeding' WHERE (`tag_id` = '175');
UPDATE `trapit`.`tag` SET `slo_name` = 'Koruza', `eng_name` = 'Corn' WHERE (`tag_id` = '176');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mrhovina', `eng_name` = 'Carrion' WHERE (`tag_id` = '177');
UPDATE `trapit`.`tag` SET `slo_name` = 'Solnica', `eng_name` = 'Salt Lick' WHERE (`tag_id` = '178');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jabolka', `eng_name` = 'Apples' WHERE (`tag_id` = '179');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tropine', `eng_name` = 'Grape Skins' WHERE (`tag_id` = '180');
UPDATE `trapit`.`tag` SET `slo_name` = 'Seno', `eng_name` = 'Hay' WHERE (`tag_id` = '181');
UPDATE `trapit`.`tag` SET `slo_name` = 'Sladkorna Pesa', `eng_name` = 'Sugar Beet' WHERE (`tag_id` = '182');
UPDATE `trapit`.`tag` SET `slo_name` = 'Slaščičarski Ostanki', `eng_name` = 'Bakery Leftovers' WHERE (`tag_id` = '183');
UPDATE `trapit`.`tag` SET `slo_name` = 'Druga Vaba', `eng_name` = 'Other Bait' WHERE (`tag_id` = '184');
UPDATE `trapit`.`tag` SET `slo_name` = 'Individual ID', `eng_name` = 'Individual ID' WHERE (`tag_id` = '185');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lojze', `eng_name` = 'Lojze' WHERE (`tag_id` = '186');
UPDATE `trapit`.`tag` SET `slo_name` = 'Rudi', `eng_name` = 'Rudi' WHERE (`tag_id` = '187');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pepa', `eng_name` = 'Pepa' WHERE (`tag_id` = '188');
UPDATE `trapit`.`tag` SET `slo_name` = 'Interakcije', `eng_name` = 'Interactions' WHERE (`tag_id` = '189');
UPDATE `trapit`.`tag` SET `slo_name` = 'Znotrajvrstne', `eng_name` = 'Intraspecific' WHERE (`tag_id` = '190');
UPDATE `trapit`.`tag` SET `slo_name` = 'Medvrstne', `eng_name` = 'Interspecific' WHERE (`tag_id` = '191');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelenjad', `eng_name` = 'Deer' WHERE (`tag_id` = '192');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tele', `eng_name` = 'Calf' WHERE (`tag_id` = '193');
UPDATE `trapit`.`tag` SET `slo_name` = 'Junica', `eng_name` = 'Heifer' WHERE (`tag_id` = '194');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '195');
UPDATE `trapit`.`tag` SET `slo_name` = 'Košuta', `eng_name` = 'Hind' WHERE (`tag_id` = '196');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen', `eng_name` = 'Red Deer' WHERE (`tag_id` = '197');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(2-4)', `eng_name` = 'Stag(2-4)' WHERE (`tag_id` = '198');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(5-10)', `eng_name` = 'Stag(5-10)' WHERE (`tag_id` = '199');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(10+)', `eng_name` = 'Stag(10+)' WHERE (`tag_id` = '200');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjad', `eng_name` = 'Deer' WHERE (`tag_id` = '201');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '202');
UPDATE `trapit`.`tag` SET `slo_name` = 'Gumbar', `eng_name` = 'Young Deer' WHERE (`tag_id` = '203');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '204');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladica', `eng_name` = 'Juvenile' WHERE (`tag_id` = '205');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srna', `eng_name` = 'Doe' WHERE (`tag_id` = '206');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjak', `eng_name` = 'Buck' WHERE (`tag_id` = '207');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjak (srednje star)', `eng_name` = 'Buck (middle-age)' WHERE (`tag_id` = '208');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srnjak (star)', `eng_name` = 'Buck (old)' WHERE (`tag_id` = '209');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divji Prašič', `eng_name` = 'Wild Boar' WHERE (`tag_id` = '210');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '211');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ozimec', `eng_name` = 'Young Boar' WHERE (`tag_id` = '212');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '213');
UPDATE `trapit`.`tag` SET `slo_name` = 'Svinja', `eng_name` = 'Pig' WHERE (`tag_id` = '214');
UPDATE `trapit`.`tag` SET `slo_name` = 'Merjasec', `eng_name` = 'Boar' WHERE (`tag_id` = '215');
UPDATE `trapit`.`tag` SET `slo_name` = 'Rjavi Medved', `eng_name` = 'Brown Bear' WHERE (`tag_id` = '216');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '217');
UPDATE `trapit`.`tag` SET `slo_name` = 'Medvedka', `eng_name` = 'Bear (female)' WHERE (`tag_id` = '218');
UPDATE `trapit`.`tag` SET `slo_name` = 'Medved', `eng_name` = 'Bear (male)' WHERE (`tag_id` = '219');
UPDATE `trapit`.`tag` SET `slo_name` = '200kg+', `eng_name` = '200kg+' WHERE (`tag_id` = '220');
UPDATE `trapit`.`tag` SET `slo_name` = 'Damjek', `eng_name` = 'Fallow Deer' WHERE (`tag_id` = '221');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tele', `eng_name` = 'Calf' WHERE (`tag_id` = '222');
UPDATE `trapit`.`tag` SET `slo_name` = 'Junica', `eng_name` = 'Heifer' WHERE (`tag_id` = '223');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lanščak', `eng_name` = 'Hart' WHERE (`tag_id` = '224');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(2-4)', `eng_name` = 'Stag(2-4)' WHERE (`tag_id` = '225');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(5-10)', `eng_name` = 'Stag(5-10)' WHERE (`tag_id` = '226');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jelen(10+)', `eng_name` = 'Stag(10+)' WHERE (`tag_id` = '227');
UPDATE `trapit`.`tag` SET `slo_name` = 'Košuta', `eng_name` = 'Hind' WHERE (`tag_id` = '228');
UPDATE `trapit`.`tag` SET `slo_name` = 'Gams', `eng_name` = 'Chamois' WHERE (`tag_id` = '229');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '230');
UPDATE `trapit`.`tag` SET `slo_name` = 'Koza', `eng_name` = 'Goat (female)' WHERE (`tag_id` = '231');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozel', `eng_name` = 'Goat (male)' WHERE (`tag_id` = '232');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozorog', `eng_name` = 'Alpine Ibex' WHERE (`tag_id` = '233');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '234');
UPDATE `trapit`.`tag` SET `slo_name` = 'Koza', `eng_name` = 'Goat (female)' WHERE (`tag_id` = '235');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozel', `eng_name` = 'Goat (male)' WHERE (`tag_id` = '236');
UPDATE `trapit`.`tag` SET `slo_name` = 'Muflon', `eng_name` = 'Mouflon' WHERE (`tag_id` = '237');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '238');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ovca', `eng_name` = 'Sheep' WHERE (`tag_id` = '239');
UPDATE `trapit`.`tag` SET `slo_name` = 'Oven', `eng_name` = 'Ram' WHERE (`tag_id` = '240');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ptica pevka', `eng_name` = 'Songbird' WHERE (`tag_id` = '241');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ščinkavec', `eng_name` = 'Finch' WHERE (`tag_id` = '242');
UPDATE `trapit`.`tag` SET `slo_name` = 'Brglez', `eng_name` = 'Nuthach' WHERE (`tag_id` = '243');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kos', `eng_name` = 'Blackbird' WHERE (`tag_id` = '244');
UPDATE `trapit`.`tag` SET `slo_name` = 'Šoja', `eng_name` = 'Eurasian Jay' WHERE (`tag_id` = '245');
UPDATE `trapit`.`tag` SET `slo_name` = 'Velika Sinica', `eng_name` = 'Great Tit' WHERE (`tag_id` = '246');
UPDATE `trapit`.`tag` SET `slo_name` = 'Krokar', `eng_name` = 'Raven' WHERE (`tag_id` = '247');
UPDATE `trapit`.`tag` SET `slo_name` = 'Menišček', `eng_name` = 'Coal Tit' WHERE (`tag_id` = '248');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ujeda', `eng_name` = 'Raptor' WHERE (`tag_id` = '249');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kanja', `eng_name` = 'Buzzard' WHERE (`tag_id` = '250');
UPDATE `trapit`.`tag` SET `slo_name` = 'Belorepec', `eng_name` = 'White-tailed Eagle' WHERE (`tag_id` = '251');
UPDATE `trapit`.`tag` SET `slo_name` = 'Skobec', `eng_name` = 'Sparrowhawk' WHERE (`tag_id` = '252');
UPDATE `trapit`.`tag` SET `slo_name` = 'Planinski Orel', `eng_name` = 'Golden Eagle' WHERE (`tag_id` = '253');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kragulj', `eng_name` = 'Goshawk' WHERE (`tag_id` = '254');
UPDATE `trapit`.`tag` SET `slo_name` = 'Sova', `eng_name` = 'Owl' WHERE (`tag_id` = '255');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kozača', `eng_name` = 'Ural Owl' WHERE (`tag_id` = '256');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lesna Sova', `eng_name` = 'Trawny Owl' WHERE (`tag_id` = '257');
UPDATE `trapit`.`tag` SET `slo_name` = 'Velika Uharica', `eng_name` = 'Eagle Owl' WHERE (`tag_id` = '258');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pegasta Sova', `eng_name` = 'Barn Owl' WHERE (`tag_id` = '259');
UPDATE `trapit`.`tag` SET `slo_name` = 'Čuk', `eng_name` = 'Little Owl' WHERE (`tag_id` = '260');
UPDATE `trapit`.`tag` SET `slo_name` = 'Veliki Skovik', `eng_name` = 'Eurasian Scops Owl' WHERE (`tag_id` = '261');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mali Skovik', `eng_name` = 'Eurasian Pygmy Owl' WHERE (`tag_id` = '262');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mala Uharica', `eng_name` = 'Long-eared Owl' WHERE (`tag_id` = '263');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kura', `eng_name` = 'Hen' WHERE (`tag_id` = '264');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divji Petelin', `eng_name` = 'Western Capercaillie' WHERE (`tag_id` = '265');
UPDATE `trapit`.`tag` SET `slo_name` = 'Gozdni Jereb', `eng_name` = 'Hazel Grouse' WHERE (`tag_id` = '266');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ruševec', `eng_name` = 'Black Grouse' WHERE (`tag_id` = '267');
UPDATE `trapit`.`tag` SET `slo_name` = 'Fazan', `eng_name` = 'Pheasant' WHERE (`tag_id` = '268');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jerebica', `eng_name` = 'Grey Partridge' WHERE (`tag_id` = '269');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kotorna', `eng_name` = 'Rock Partridge' WHERE (`tag_id` = '270');
UPDATE `trapit`.`tag` SET `slo_name` = 'Belka', `eng_name` = 'Ptarmigan' WHERE (`tag_id` = '271');
UPDATE `trapit`.`tag` SET `slo_name` = 'Golob', `eng_name` = 'Pidgeon' WHERE (`tag_id` = '272');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divja Grlica', `eng_name` = 'Turtle Dove' WHERE (`tag_id` = '273');
UPDATE `trapit`.`tag` SET `slo_name` = 'Duplar', `eng_name` = 'Stock Dove' WHERE (`tag_id` = '274');
UPDATE `trapit`.`tag` SET `slo_name` = 'Grivar', `eng_name` = 'Wood Pidgeon' WHERE (`tag_id` = '275');
UPDATE `trapit`.`tag` SET `slo_name` = 'Žolna', `eng_name` = 'Woodpecker' WHERE (`tag_id` = '276');
UPDATE `trapit`.`tag` SET `slo_name` = 'Črna Žolna', `eng_name` = 'Black Woodpecker' WHERE (`tag_id` = '277');
UPDATE `trapit`.`tag` SET `slo_name` = 'Zelena Žolna', `eng_name` = 'European Green Woodpecker' WHERE (`tag_id` = '278');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pivka', `eng_name` = 'Grey-headed Woodpecker' WHERE (`tag_id` = '279');
UPDATE `trapit`.`tag` SET `slo_name` = 'Veliki Detel', `eng_name` = 'Great Spotted Woodpecker' WHERE (`tag_id` = '280');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mali Detel', `eng_name` = 'Lesser Spotted Woodpecker' WHERE (`tag_id` = '281');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srednji Detel', `eng_name` = 'Middle Spotted Woodpecker' WHERE (`tag_id` = '282');
UPDATE `trapit`.`tag` SET `slo_name` = 'Belohrbti Detel', `eng_name` = 'White-tailed Woodpecker' WHERE (`tag_id` = '283');
UPDATE `trapit`.`tag` SET `slo_name` = 'Triprsti Detel', `eng_name` = 'Three-toed Woodpecker' WHERE (`tag_id` = '284');
UPDATE `trapit`.`tag` SET `slo_name` = 'Volk', `eng_name` = 'Wolf' WHERE (`tag_id` = '285');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '286');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '287');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '288');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '289');
UPDATE `trapit`.`tag` SET `slo_name` = 'Kuna', `eng_name` = 'Marten' WHERE (`tag_id` = '290');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '291');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '292');
UPDATE `trapit`.`tag` SET `slo_name` = 'Šakal', `eng_name` = 'Jackal' WHERE (`tag_id` = '293');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '294');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '295');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '296');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '297');
UPDATE `trapit`.`tag` SET `slo_name` = 'Divja Mačka', `eng_name` = 'Wildcat' WHERE (`tag_id` = '298');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '299');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '300');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ris', `eng_name` = 'Eurasian Lynx' WHERE (`tag_id` = '301');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '302');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '303');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '304');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '305');
UPDATE `trapit`.`tag` SET `slo_name` = 'Los', `eng_name` = 'Moose' WHERE (`tag_id` = '306');
UPDATE `trapit`.`tag` SET `slo_name` = 'Tele', `eng_name` = 'Calf' WHERE (`tag_id` = '307');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '308');
UPDATE `trapit`.`tag` SET `slo_name` = 'Samec', `eng_name` = 'Male' WHERE (`tag_id` = '309');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vidra', `eng_name` = 'Otter' WHERE (`tag_id` = '310');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '311');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '312');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jazbec', `eng_name` = 'Badger' WHERE (`tag_id` = '313');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '314');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '315');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lisica', `eng_name` = 'Fox' WHERE (`tag_id` = '316');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '317');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '318');
UPDATE `trapit`.`tag` SET `slo_name` = 'Rosomah', `eng_name` = 'Wolverine' WHERE (`tag_id` = '319');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '320');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '321');
UPDATE `trapit`.`tag` SET `slo_name` = 'Bober', `eng_name` = 'Beaver' WHERE (`tag_id` = '322');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mladič', `eng_name` = 'Juvenile' WHERE (`tag_id` = '323');
UPDATE `trapit`.`tag` SET `slo_name` = 'Odrasel', `eng_name` = 'Adult' WHERE (`tag_id` = '324');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pes', `eng_name` = 'Dog' WHERE (`tag_id` = '325');
UPDATE `trapit`.`tag` SET `slo_name` = 'Domača Mačka', `eng_name` = 'Feral Cat' WHERE (`tag_id` = '326');
UPDATE `trapit`.`tag` SET `slo_name` = 'Veverica', `eng_name` = 'Squirrel' WHERE (`tag_id` = '327');
UPDATE `trapit`.`tag` SET `slo_name` = 'Polh', `eng_name` = 'Dormouse' WHERE (`tag_id` = '328');
UPDATE `trapit`.`tag` SET `slo_name` = 'Jež', `eng_name` = 'European Hedgehog' WHERE (`tag_id` = '329');
UPDATE `trapit`.`tag` SET `slo_name` = 'Zober', `eng_name` = 'European Bison' WHERE (`tag_id` = '330');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mink', `eng_name` = 'American Mink' WHERE (`tag_id` = '331');
UPDATE `trapit`.`tag` SET `slo_name` = 'Nutrija', `eng_name` = 'Nutria' WHERE (`tag_id` = '332');
UPDATE `trapit`.`tag` SET `slo_name` = 'Pižmovka', `eng_name` = 'Muskrat' WHERE (`tag_id` = '333');
UPDATE `trapit`.`tag` SET `slo_name` = 'Podlasica', `eng_name` = 'Weasel' WHERE (`tag_id` = '334');
UPDATE `trapit`.`tag` SET `slo_name` = 'Drugi Sesalci', `eng_name` = 'Other Mamals' WHERE (`tag_id` = '335');
UPDATE `trapit`.`tag` SET `slo_name` = 'Poljski Zajec', `eng_name` = 'Hare' WHERE (`tag_id` = '336');
UPDATE `trapit`.`tag` SET `slo_name` = 'Nedoločljiva', `eng_name` = 'Indistinguishable' WHERE (`tag_id` = '337');
UPDATE `trapit`.`tag` SET `slo_name` = 'Brez Živali', `eng_name` = 'No Animals' WHERE (`tag_id` = '338');
UPDATE `trapit`.`tag` SET `slo_name` = 'Človeška Aktivnost', `eng_name` = 'Human Activity' WHERE (`tag_id` = '339');
UPDATE `trapit`.`tag` SET `slo_name` = 'Nošnja Hrane', `eng_name` = 'Carrying Food' WHERE (`tag_id` = '340');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vzdrževanje Kamere', `eng_name` = 'Camera Maintenance' WHERE (`tag_id` = '341');
UPDATE `trapit`.`tag` SET `slo_name` = 'Prinašanje Hrane', `eng_name` = 'Bringing Food' WHERE (`tag_id` = '342');
UPDATE `trapit`.`tag` SET `slo_name` = 'Prehajanje', `eng_name` = 'Crossing' WHERE (`tag_id` = '343');
UPDATE `trapit`.`tag` SET `slo_name` = 'Sečnja', `eng_name` = 'Logging' WHERE (`tag_id` = '344');
UPDATE `trapit`.`tag` SET `slo_name` = 'Košnja', `eng_name` = 'Mowing' WHERE (`tag_id` = '345');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vožnja', `eng_name` = 'Driving' WHERE (`tag_id` = '346');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ogledovanje', `eng_name` = 'Inspecting' WHERE (`tag_id` = '347');
UPDATE `trapit`.`tag` SET `slo_name` = 'Lov', `eng_name` = 'Hunt' WHERE (`tag_id` = '348');
UPDATE `trapit`.`tag` SET `slo_name` = 'Drugo Delo', `eng_name` = 'Other Work' WHERE (`tag_id` = '349');
UPDATE `trapit`.`tag` SET `slo_name` = 'Moteči Faktorji', `eng_name` = 'Distracting Factors' WHERE (`tag_id` = '350');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vreme', `eng_name` = 'Weather' WHERE (`tag_id` = '351');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vegetacija', `eng_name` = 'Vegetation' WHERE (`tag_id` = '352');
UPDATE `trapit`.`tag` SET `slo_name` = 'Premik Kamere', `eng_name` = 'Camera Moved' WHERE (`tag_id` = '353');
UPDATE `trapit`.`tag` SET `slo_name` = 'Okvara Kamere', `eng_name` = 'Camera Malfunction' WHERE (`tag_id` = '354');
UPDATE `trapit`.`tag` SET `slo_name` = 'Ostalo', `eng_name` = 'Other' WHERE (`tag_id` = '355');
UPDATE `trapit`.`tag` SET `slo_name` = 'Vreme', `eng_name` = 'Weather' WHERE (`tag_id` = '356');
UPDATE `trapit`.`tag` SET `slo_name` = 'Toča', `eng_name` = 'Hail' WHERE (`tag_id` = '357');
UPDATE `trapit`.`tag` SET `slo_name` = 'Megla', `eng_name` = 'Fog' WHERE (`tag_id` = '358');
UPDATE `trapit`.`tag` SET `slo_name` = 'Sneženje', `eng_name` = 'Snowing' WHERE (`tag_id` = '359');
UPDATE `trapit`.`tag` SET `slo_name` = 'Rahlo', `eng_name` = 'Gently' WHERE (`tag_id` = '360');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srednje', `eng_name` = 'Moderately' WHERE (`tag_id` = '361');
UPDATE `trapit`.`tag` SET `slo_name` = 'Močno', `eng_name` = 'Strong' WHERE (`tag_id` = '362');
UPDATE `trapit`.`tag` SET `slo_name` = 'Dež', `eng_name` = 'Rain' WHERE (`tag_id` = '363');
UPDATE `trapit`.`tag` SET `slo_name` = 'Rahlo', `eng_name` = 'Gently' WHERE (`tag_id` = '364');
UPDATE `trapit`.`tag` SET `slo_name` = 'Srednje', `eng_name` = 'Moderately' WHERE (`tag_id` = '365');
UPDATE `trapit`.`tag` SET `slo_name` = 'Močno', `eng_name` = 'Strong' WHERE (`tag_id` = '366');
UPDATE `trapit`.`tag` SET `slo_name` = 'Napačna Ura', `eng_name` = 'Wrong Time' WHERE (`tag_id` = '367');
UPDATE `trapit`.`tag` SET `slo_name` = 'FALSE', `eng_name` = 'FALSE' WHERE (`tag_id` = '368');
UPDATE `trapit`.`tag` SET `slo_name` = 'TRUE', `eng_name` = 'TRUE' WHERE (`tag_id` = '369');
UPDATE `trapit`.`tag` SET `slo_name` = 'Dan', `eng_name` = 'Day' WHERE (`tag_id` = '370');
UPDATE `trapit`.`tag` SET `slo_name` = 'Noč', `eng_name` = 'Night' WHERE (`tag_id` = '371');
UPDATE `trapit`.`tag` SET `slo_name` = 'Mrak', `eng_name` = 'Dusk' WHERE (`tag_id` = '372');
UPDATE `trapit`.`tag` SET `slo_name` = 'Zora', `eng_name` = 'Dawn' WHERE (`tag_id` = '373');
UPDATE `trapit`.`tag` SET `slo_name` = 'Neuporabna Slika', `eng_name` = 'Useless Photo' WHERE (`tag_id` = '374');
UPDATE `trapit`.`tag` SET `slo_name` = 'TRUE', `eng_name` = 'TRUE' WHERE (`tag_id` = '375');
UPDATE `trapit`.`tag` SET `slo_name` = 'FALSE', `eng_name` = 'FALSE' WHERE (`tag_id` = '376');
UPDATE `trapit`.`tag` SET `slo_name` = 'Prisotnost Vode', `eng_name` = 'Presence of Water' WHERE (`tag_id` = '377');
UPDATE `trapit`.`tag` SET `slo_name` = 'TRUE', `eng_name` = 'TRUE' WHERE (`tag_id` = '378');
UPDATE `trapit`.`tag` SET `slo_name` = 'FALSE', `eng_name` = 'FALSE' WHERE (`tag_id` = '379');
UPDATE `trapit`.`tag` SET `slo_name` = 'Napacen Datum', `eng_name` = 'Wrong Date' WHERE (`tag_id` = '380');
UPDATE `trapit`.`tag` SET `slo_name` = 'TRUE', `eng_name` = 'TRUE' WHERE (`tag_id` = '381');
UPDATE `trapit`.`tag` SET `slo_name` = 'FALSE', `eng_name` = 'FALSE' WHERE (`tag_id` = '382');
UPDATE `trapit`.`tag` SET `slo_name` = 'Snežna Odeja', `eng_name` = 'Blanket of Snow' WHERE (`tag_id` = '383');
UPDATE `trapit`.`tag` SET `slo_name` = 'TRUE', `eng_name` = 'TRUE' WHERE (`tag_id` = '384');
UPDATE `trapit`.`tag` SET `slo_name` = 'FALSE', `eng_name` = 'FALSE' WHERE (`tag_id` = '385');
