-- MySQL Script generated by MySQL Workbench
-- Sat Jun 30 18:18:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trapit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trapit` ;

-- -----------------------------------------------------
-- Schema trapit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trapit` DEFAULT CHARACTER SET utf8 ;
USE `trapit` ;

-- -----------------------------------------------------
-- Table `trapit`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`role` ;

CREATE TABLE IF NOT EXISTS `trapit`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`user` ;

CREATE TABLE IF NOT EXISTS `trapit`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(150) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `role_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `user_role_fk_idx` (`role_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `user_role_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `trapit`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`site` ;

CREATE TABLE IF NOT EXISTS `trapit`.`site` (
  `site_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`site_id`),
  UNIQUE INDEX `site_id_UNIQUE` (`site_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`path`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`path` ;

CREATE TABLE IF NOT EXISTS `trapit`.`path` (
  `path_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`path_id`),
  UNIQUE INDEX `path_id_UNIQUE` (`path_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`media` ;

CREATE TABLE IF NOT EXISTS `trapit`.`media` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `empty` TINYINT NOT NULL DEFAULT 1,
  `image` TINYINT NOT NULL DEFAULT 1,
  `interesting` TINYINT NOT NULL,
  `comment` TEXT NULL,
  `site_id` INT NOT NULL,
  `path_id` INT NOT NULL,
  PRIMARY KEY (`media_id`),
  UNIQUE INDEX `media_id_UNIQUE` (`media_id` ASC),
  INDEX `media_site_fk_idx` (`site_id` ASC),
  INDEX `media_path_fk_idx` (`path_id` ASC),
  CONSTRAINT `media_site_fk`
    FOREIGN KEY (`site_id`)
    REFERENCES `trapit`.`site` (`site_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `media_path_fk`
    FOREIGN KEY (`path_id`)
    REFERENCES `trapit`.`path` (`path_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`tag` ;

CREATE TABLE IF NOT EXISTS `trapit`.`tag` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `parent_tag_id` INT NULL,
  `input` TINYINT NOT NULL DEFAULT 0,
  `checkbox` TINYINT NOT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC),
  INDEX `tag_parent_fk_idx` (`parent_tag_id` ASC),
  CONSTRAINT `fk_tag_parent`
    FOREIGN KEY (`parent_tag_id`)
    REFERENCES `trapit`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`media_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`media_tag` ;

CREATE TABLE IF NOT EXISTS `trapit`.`media_tag` (
  `media_tag_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  `input_value` INT NULL,
  UNIQUE INDEX `media_tag_id_UNIQUE` (`media_tag_id` ASC),
  PRIMARY KEY (`media_tag_id`),
  INDEX `media_tag_user_fk_idx` (`user_id` ASC),
  INDEX `media_tag_tag_fk_idx` (`tag_id` ASC),
  INDEX `media_tag_media_fk_idx` (`media_id` ASC),
  CONSTRAINT `media_tag_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `trapit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `media_tag_tag_fk`
    FOREIGN KEY (`tag_id`)
    REFERENCES `trapit`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `media_tag_media_fk`
    FOREIGN KEY (`media_id`)
    REFERENCES `trapit`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`project` ;

CREATE TABLE IF NOT EXISTS `trapit`.`project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trapit`.`project_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trapit`.`project_tag` ;

CREATE TABLE IF NOT EXISTS `trapit`.`project_tag` (
  `project_tag_id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`project_tag_id`),
  INDEX `project_tag_tag_fk_idx` (`tag_id` ASC),
  UNIQUE INDEX `project_tag_id_UNIQUE` (`project_tag_id` ASC),
  CONSTRAINT `project_tag_project_fk`
    FOREIGN KEY (`project_id`)
    REFERENCES `trapit`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_tag_tag_fk`
    FOREIGN KEY (`tag_id`)
    REFERENCES `trapit`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into site(name)values("17_Janezova_koca");

insert into path(value)values("V:/2017/17_Janezova_koca");

insert into tag (name, parent_tag_id, input, checkbox) values ("kategorija", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("jelenjad", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("srnjad", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("divji_prašič", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("rjavi_medved", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("damjak", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("gams", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("muflon", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("pitca_pevka", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("ujeda", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("sova", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("kura", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("golobi", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("žolne", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("vse_ostale_vrste", (select tag_id from (select * from tag) as tempTable where name="kategorija" and parent_tag_id is null), 1, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("vrsta", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("jelenjad", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("tele", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("junica", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("lanščak", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(2-4)", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(5-10)", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(10+)", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("košuta", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("srnjad", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("gubar", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("lanščak", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladica", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("srna", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("srnjak(srednje_star)", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("srnjak(star)", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("divji_prašič", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("ozimec", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("lanščak", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("svinja", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("merjasec", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("rjavi_medved", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladič_0+", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladič_1+", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("medvedka", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("medved", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("200kg+", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("damjak", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("tele", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("junica", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("lanšlak", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(2-4)", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(5-10)", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(10+)", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("košuta", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("gams", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="gams" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("koza", (select tag_id from (select * from tag) as tempTable where name="gams" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("kozel", (select tag_id from (select * from tag) as tempTable where name="gams" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("muflon", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="muflon" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("ovca", (select tag_id from (select * from tag) as tempTable where name="muflon" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("oven", (select tag_id from (select * from tag) as tempTable where name="muflon" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("ptica_pevka", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("ščinkavec", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("brglez", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("kos", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("šoja", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("velika_sinica", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("krokar", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("menišček", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("ujeda", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("ščinkavec", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("brglez", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("kos", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("šoja", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("velika_sinica", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("krokar", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("menišček", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("sova", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("kozača", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("lesna_sova", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("velika_uharica", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("pegasta_sova", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("čuk", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("veliki_skovik", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mali_skovik", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mala_uharica", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("kura", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("divji_petelin", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("gozdni_jereb", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("ruševec", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("fazan", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jerebica", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("kotorna", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("belka", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("golobi", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("divja_grlica", (select tag_id from (select * from tag) as tempTable where name="golobi" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("duplar", (select tag_id from (select * from tag) as tempTable where name="golobi" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("grivar", (select tag_id from (select * from tag) as tempTable where name="golobi" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("žolne", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("črna_žolna", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("zelena_žolna", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("pivka", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("veliki_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mali_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("srednji_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("belohrbti_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("triprsti_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("vse_ostale_vrste", (select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="vse_ostale_vrste" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("odrasel", (select tag_id from (select * from tag) as tempTable where name="vse_ostale_vrste" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vrsta" and parent_tag_id is null)), 1, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("število", null, 1, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("vaba", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("brez_vabe", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("koruza", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("mrhovina", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("solnica", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("jabolka", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("tropine", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("seno", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("sladkorna_pesa", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("slaščičarski_ostanki", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("druga_vaba", (select tag_id from (select * from tag) as tempTable where name="vaba" and parent_tag_id is null), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("vedenje", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("pitje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("parjenje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("bojevanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("prehajanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("vohanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("opazovanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("iztrebljanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("kopanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("lov", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("oglašanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("markiranje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("valjanje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("drugo", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("hranjenje", (select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("koruza", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mrhovina", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("solnica", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jabolka", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("tropine", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("seno", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("sladkorna_pesa", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("slaščičarski_ostanki", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("druga_vaba", (select tag_id from (select * from tag) as tempTable where name="hranjenje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vedenje" and parent_tag_id is null)), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("individual_id", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("Lojza", (select tag_id from (select * from tag) as tempTable where name="individual_id" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("Rudi", (select tag_id from (select * from tag) as tempTable where name="individual_id" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("Pepa", (select tag_id from (select * from tag) as tempTable where name="individual_id" and parent_tag_id is null), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("interakcije", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("znotrajvrstne", (select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("medvrstne", (select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("jelenjad", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("tele", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("junica", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("lanščak", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(2-4)", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(5-10)", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(10+)", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("košuta", (select tag_id from (select * from tag) as tempTable where name="jelenjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("srnjad", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("gubar", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("lanščak", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladica", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("srna", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("srnjak(srednje_star)", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("srnjak(star)", (select tag_id from (select * from tag) as tempTable where name="srnjad" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("divji_prašič", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("ozimec", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("lanščak", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("svinja", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("merjasec", (select tag_id from (select * from tag) as tempTable where name="divji_prašič" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("rjavi_medved", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladič_0+", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladič_1+", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("medvedka", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("medved", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("200kg+", (select tag_id from (select * from tag) as tempTable where name="rjavi_medved" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("damjak", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("tele", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("junica", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("lanšlak", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(2-4)", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(5-10)", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("jelen(10+)", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("košuta", (select tag_id from (select * from tag) as tempTable where name="damjak" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("gams", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="gams" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("koza", (select tag_id from (select * from tag) as tempTable where name="gams" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("kozel", (select tag_id from (select * from tag) as tempTable where name="gams" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("muflon", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="muflon" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("ovca", (select tag_id from (select * from tag) as tempTable where name="muflon" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("oven", (select tag_id from (select * from tag) as tempTable where name="muflon" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("ptica_pevka", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("ščinkavec", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("brglez", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("kos", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("šoja", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("velika_sinica", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("krokar", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("menišček", (select tag_id from (select * from tag) as tempTable where name="ptica_pevka" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("ujeda", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("ščinkavec", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("brglez", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("kos", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("šoja", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("velika_sinica", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("krokar", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("menišček", (select tag_id from (select * from tag) as tempTable where name="ujeda" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("sova", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("kozača", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("lesna_sova", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("velika_uharica", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("pegasta_sova", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("čuk", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("veliki_skovik", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mali_skovik", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mala_uharica", (select tag_id from (select * from tag) as tempTable where name="sova" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("kura", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("divji_petelin", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("gozdni_jereb", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("ruševec", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("fazan", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("jerebica", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("kotorna", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("belka", (select tag_id from (select * from tag) as tempTable where name="kura" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("golobi", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("divja_grlica", (select tag_id from (select * from tag) as tempTable where name="golobi" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("duplar", (select tag_id from (select * from tag) as tempTable where name="golobi" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("grivar", (select tag_id from (select * from tag) as tempTable where name="golobi" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("žolne", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("črna_žolna", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("zelena_žolna", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("pivka", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("veliki_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mali_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("srednji_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("belohrbti_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("triprsti_detel", (select tag_id from (select * from tag) as tempTable where name="žolne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("vse_ostale_vrste", (select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null)), 0, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("mladič", (select tag_id from (select * from tag) as tempTable where name="vse_ostale_vrste" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
			insert into tag (name, parent_tag_id, input, checkbox) values ("odrasel", (select tag_id from (select * from tag) as tempTable where name="vse_ostale_vrste" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="medvrstne" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="interakcije" and parent_tag_id is null))), 1, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("človeška_aktivnost", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("vzdrževanje_kamere", (select tag_id from (select * from tag) as tempTable where name="človeška_aktivnost" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("prinašanje_hrane", (select tag_id from (select * from tag) as tempTable where name="človeška_aktivnost" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("prehajanje", (select tag_id from (select * from tag) as tempTable where name="človeška_aktivnost" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("sečnja", (select tag_id from (select * from tag) as tempTable where name="človeška_aktivnost" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("košnja", (select tag_id from (select * from tag) as tempTable where name="človeška_aktivnost" and parent_tag_id is null), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("moteči_faktorji", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("vreme", (select tag_id from (select * from tag) as tempTable where name="moteči_faktorji" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("vegetacija", (select tag_id from (select * from tag) as tempTable where name="moteči_faktorji" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("premik_kamere", (select tag_id from (select * from tag) as tempTable where name="moteči_faktorji" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("okvara_kamere", (select tag_id from (select * from tag) as tempTable where name="moteči_faktorji" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("ostalo", (select tag_id from (select * from tag) as tempTable where name="moteči_faktorji" and parent_tag_id is null), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("vreme", null, 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("toča", (select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("megla", (select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("sneženje", (select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("rahlo", (select tag_id from (select * from tag) as tempTable where name="sneženje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("srednje", (select tag_id from (select * from tag) as tempTable where name="sneženje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("močno", (select tag_id from (select * from tag) as tempTable where name="sneženje" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null)), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("dež", (select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("rahlo", (select tag_id from (select * from tag) as tempTable where name="dež" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("srednje", (select tag_id from (select * from tag) as tempTable where name="dež" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("močno", (select tag_id from (select * from tag) as tempTable where name="dež" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="vreme" and parent_tag_id is null)), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("napačna_ura", null, 0, 1);
	insert into tag (name, parent_tag_id, input, checkbox) values ("false", (select tag_id from (select * from tag) as tempTable where name="napačna_ura" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("true", (select tag_id from (select * from tag) as tempTable where name="napačna_ura" and parent_tag_id is null), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("dan", (select tag_id from (select * from tag) as tempTable where name="true" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="napačna_ura" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("noč", (select tag_id from (select * from tag) as tempTable where name="true" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="napačna_ura" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("mrak", (select tag_id from (select * from tag) as tempTable where name="true" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="napačna_ura" and parent_tag_id is null)), 0, 0);
		insert into tag (name, parent_tag_id, input, checkbox) values ("zora", (select tag_id from (select * from tag) as tempTable where name="true" and parent_tag_id=(select tag_id from (select * from tag) as tempTable where name="napačna_ura" and parent_tag_id is null)), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("prisotnost_vode", null, 0, 1);
	insert into tag (name, parent_tag_id, input, checkbox) values ("true", (select tag_id from (select * from tag) as tempTable where name="prisotnost_vode" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("false", (select tag_id from (select * from tag) as tempTable where name="prisotnost_vode" and parent_tag_id is null), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("napačen_datum", null, 0, 1);
	insert into tag (name, parent_tag_id, input, checkbox) values ("true", (select tag_id from (select * from tag) as tempTable where name="napačen_datum" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("false", (select tag_id from (select * from tag) as tempTable where name="napačen_datum" and parent_tag_id is null), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("snežna_odeja", null, 0, 1);
	insert into tag (name, parent_tag_id, input, checkbox) values ("true", (select tag_id from (select * from tag) as tempTable where name="snežna_odeja" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("false", (select tag_id from (select * from tag) as tempTable where name="snežna_odeja" and parent_tag_id is null), 0, 0);
insert into tag (name, parent_tag_id, input, checkbox) values ("zanimiva_fotografija", null, 0, 1);
	insert into tag (name, parent_tag_id, input, checkbox) values ("true", (select tag_id from (select * from tag) as tempTable where name="zanimiva_fotografija" and parent_tag_id is null), 0, 0);
	insert into tag (name, parent_tag_id, input, checkbox) values ("false", (select tag_id from (select * from tag) as tempTable where name="zanimiva_fotografija" and parent_tag_id is null), 0, 0);

INSERT INTO trapit.role VALUES
    (1, "admin"),
    (2, "reviewer"),
    (3, "viewer"); 

INSERT INTO trapit.project VALUES
    (1, "project1"),
    (2, "project2"),
    (3, "project3");  

INSERT INTO trapit.user
    (user_id, username, password, role_id)
VALUES
    (1, "admin", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 1),
    (2, "reviewer", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 2),
    (3, "viewer", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (4, "Dejan Bordjan", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (5, "Urša Fležar", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 1),
    (6, "Jernej Javornik", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (7, "Lovro Stopar", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (8, "Tadej Murn", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (9, "Frowin Feurstein", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (10, "Gregor Marolt", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (11, "Miha Predalič", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3),
    (12, "Lan Hočevar", "$2b$10$AP4xtsOur0knwrq1ObleYekiJ52Z482DxXTmEXKRA7DFfSuGSFnu2", 3);

